name: Open Story

on:
  push:
    branches:
      - main
      - stag

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.KEY }}
          aws-secret-access-key: ${{ secrets.SECRET }}
          aws-region: sa-east-1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Deploy
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: aws s3 sync ./dist/browser s3://otherparty.ai

      - name: Deploy Staging
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/stag'
        run: aws s3 sync ./dist/browser s3://stag.otherparty.ai

  invalidate:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.KEY }}
          aws-secret-access-key: ${{ secrets.SECRET }}
          aws-region: sa-east-1

      - name: Create CloudFront Invalidation staging
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/stag'   
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1EA02UAUYUUZV \
            --paths "/*"

      - name: Create CloudFront Invalidation Production
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E35L6PX7JFC2TF \
            --paths "/*"
